#!/usr/bin/env python3
"""
Validate index.xml against the ReaPack repository index format.

Background (docs-audit P1-4): the hand-written index used ``version="1.0"``,
no ``commit`` attribute, a ``<description>`` child inside ``<category>``
(not part of the format), ``type`` on ``<version>``, and inverted ``<source>``
elements (the body must be the file to download, and the ``main``/``file``
attribute is the installed filename).

Reference: indexes generated by https://github.com/cfillion/reapack-index,
e.g. https://acendan.github.io/reascripts/index.xml

Usage:
    python tools/check_index.py [path/to/index.xml]
"""

from __future__ import annotations

import datetime as dt
import sys
import xml.etree.ElementTree as ET  # nosec B405
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _tag(element: ET.Element) -> str:
    """Local tag name, ignoring any XML namespace."""
    return element.tag.rsplit("}", 1)[-1]


def _children(element: ET.Element) -> list[ET.Element]:
    return [child for child in element if isinstance(child.tag, str)]


def _findall(element: ET.Element, tag: str) -> list[ET.Element]:
    return [child for child in _children(element) if _tag(child) == tag]


def check_index(path: Path) -> list[str]:
    """Return a list of human-readable problems (empty means the index is valid)."""
    problems: list[str] = []

    try:
        root = ET.parse(path).getroot()  # nosec B314
    except ET.ParseError as e:
        return [f"index.xml is not well-formed XML: {e}"]

    if _tag(root) != "index":
        problems.append(f"root element is <{root.tag}>, expected <index>")
        return problems

    if root.get("version") != "1":
        problems.append(f'root version="{root.get("version")}" — ReaPack expects version="1"')

    if not root.get("name"):
        problems.append("root is missing the repository name attribute")

    commit = root.get("commit") or ""
    if len(commit) != 40 or any(c not in "0123456789abcdef" for c in commit.lower()):
        problems.append("root is missing a 40-character commit sha (written by reapack-index)")

    for category in _findall(root, "category"):
        # The published format only has <reapack> packages inside a category;
        # anything else (e.g. the old hand-written <description>) is invalid.
        unexpected = [c for c in _children(category) if _tag(c) != "reapack"]
        if unexpected:
            problems.append(
                f"<category name={category.get('name')!r}> has unexpected children "
                f"{[_tag(c) for c in unexpected]}; only <reapack> is allowed"
            )

    packages = [
        package
        for category in _findall(root, "category")
        for package in _findall(category, "reapack")
    ]
    if not packages:
        problems.append("no <reapack> packages found under <category>")

    for package in packages:
        name = package.get("name") or "(unnamed)"
        if package.get("type") != "script":
            problems.append(f"{name}: type={package.get('type')!r}, expected 'script'")
        if not package.get("desc"):
            problems.append(f"{name}: missing desc attribute")

        versions = _findall(package, "version")
        if not versions:
            problems.append(f"{name}: no <version> element")

        for version in versions:
            vname = version.get("name") or "(unnamed)"
            if not version.get("author"):
                problems.append(f"{name} {vname}: missing author")
            if version.get("type") is not None:
                problems.append(f"{name} {vname}: 'type' is not a <version> attribute")
            time = version.get("time") or ""
            if not time.endswith("Z"):
                problems.append(f"{name} {vname}: time={time!r} must be ISO8601 UTC")
            else:
                try:
                    dt.datetime.fromisoformat(time.replace("Z", "+00:00"))
                except ValueError:
                    problems.append(f"{name} {vname}: time={time!r} is not parseable")

            sources = _findall(version, "source")
            if not sources:
                problems.append(f"{name} {vname}: no <source> element")
            for source in sources:
                target = (source.text or "").strip()
                if not target:
                    problems.append(f"{name} {vname}: empty <source>")
                    continue
                if source.get("main") is None and source.get("file") is None:
                    problems.append(
                        f"{name} {vname}: <source> needs a main= or file= attribute "
                        "(the installed filename)"
                    )
                # The body must be a downloadable location: an absolute URL, or a
                # repo-relative path that exists next to the index.
                if target.startswith(("http://", "https://")):
                    if not target.endswith((".lua", ".ext", ".jsfx", ".eel", ".reapack")):
                        problems.append(f"{name} {vname}: unexpected source target {target!r}")
                    if "/raw/" in target and "/main/" in target:
                        problems.append(
                            f"{name} {vname}: source is not commit-pinned ({target!r}); "
                            "regenerate with reapack-index"
                        )
                elif not (ROOT / target).exists():
                    problems.append(f"{name} {vname}: source path not found in repo: {target!r}")

    return problems


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    path = Path(argv[0]) if argv else ROOT / "index.xml"

    problems = check_index(path)
    if problems:
        print(f"{path} is not a valid ReaPack index:")
        for problem in problems:
            print(f"  ✗ {problem}")
        return 1

    root = ET.parse(path).getroot()  # nosec B314
    packages = [
        package
        for category in _findall(root, "category")
        for package in _findall(category, "reapack")
    ]
    print(f"{path.name} OK — {len(packages)} package(s), " f"commit {root.get('commit', '')[:8]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
